# Generated by Django 5.2.8 on 2025-11-25 15:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_google_agenda', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agenda Alimentar',
                'verbose_name_plural': 'Agendas Alimentares',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de Ingrediente',
                'verbose_name_plural': 'Categorias de Ingredientes',
            },
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_refeicao', models.IntegerField()),
                ('max_refeicao', models.IntegerField()),
                ('total_caloria', models.IntegerField()),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dieta',
                'verbose_name_plural': 'Dietas',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='RestricaoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Restrição Alimentar',
                'verbose_name_plural': 'Restrições Alimentares',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('caloria', models.IntegerField(help_text='Calorias por porção (ex: 100g).')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredientes', to='core.categoria')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
        migrations.CreateModel(
            name='IngredienteDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dieta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dieta')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.ingrediente')),
            ],
            options={
                'verbose_name': 'Ingrediente em Dieta',
                'verbose_name_plural': 'Ingredientes em Dietas',
                'unique_together': {('ingrediente', 'dieta')},
            },
        ),
        migrations.AddField(
            model_name='dieta',
            name='ingredientes_restritos',
            field=models.ManyToManyField(related_name='dietas', through='core.IngredienteDieta', to='core.ingrediente'),
        ),
        migrations.CreateModel(
            name='IngredienteListaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.ingrediente')),
            ],
            options={
                'verbose_name': 'Ingrediente em Lista de Compra',
                'verbose_name_plural': 'Ingredientes em Listas de Compra',
            },
        ),
        migrations.CreateModel(
            name='IngredienteReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.ingrediente')),
            ],
            options={
                'verbose_name': 'Ingrediente em Receita',
                'verbose_name_plural': 'Ingredientes em Receitas',
            },
        ),
        migrations.CreateModel(
            name='ListaDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ingredientes', models.ManyToManyField(related_name='listas_de_compra', through='core.IngredienteListaCompra', to='core.ingrediente')),
            ],
            options={
                'verbose_name': 'Lista de Compra',
                'verbose_name_plural': 'Listas de Compra',
            },
        ),
        migrations.AddField(
            model_name='ingredientelistacompra',
            name='lista_de_compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.listadecompra'),
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('instrucoes', models.TextField()),
                ('tempo_preparo', models.IntegerField(help_text='Tempo de preparo em minutos.')),
                ('prompt_geracao', models.TextField(blank=True, help_text='Prompt usado para gerar a receita pela IA, se aplicável.', null=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('ingredientes', models.ManyToManyField(related_name='receitas', through='core.IngredienteReceita', to='core.ingrediente')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
            },
        ),
        migrations.AddField(
            model_name='ingredientereceita',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.receita'),
        ),
        migrations.CreateModel(
            name='ReceitaRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.receita')),
            ],
            options={
                'verbose_name': 'Receita em Refeição',
                'verbose_name_plural': 'Receitas em Refeições',
            },
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tipo_refeicao', models.IntegerField(choices=[(1, 'Café da Manhã'), (2, 'Almoço'), (3, 'Jantar'), (4, 'Lanche'), (5, 'Ceia')], help_text='Tipo da refeição (Café da Manhã, Almoço, etc.).')),
                ('receitas', models.ManyToManyField(related_name='refeicoes', through='core.ReceitaRefeicao', to='core.receita')),
            ],
            options={
                'verbose_name': 'Refeição',
                'verbose_name_plural': 'Refeições',
            },
        ),
        migrations.AddField(
            model_name='receitarefeicao',
            name='refeicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.refeicao'),
        ),
        migrations.CreateModel(
            name='RefeicaoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_alimentar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agendaalimentar')),
                ('refeicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.refeicao')),
            ],
            options={
                'verbose_name': 'Refeição em Agenda',
                'verbose_name_plural': 'Refeições em Agendas',
                'unique_together': {('agenda_alimentar', 'refeicao')},
            },
        ),
        migrations.AddField(
            model_name='refeicao',
            name='agendas',
            field=models.ManyToManyField(related_name='refeicoes_agendadas', through='core.RefeicaoAgenda', to='core.agendaalimentar'),
        ),
        migrations.CreateModel(
            name='RefeicaoDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dieta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dieta')),
                ('refeicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.refeicao')),
            ],
            options={
                'verbose_name': 'Refeição em Dieta',
                'verbose_name_plural': 'Refeições em Dietas',
                'unique_together': {('dieta', 'refeicao')},
            },
        ),
        migrations.AddField(
            model_name='refeicao',
            name='dietas',
            field=models.ManyToManyField(related_name='refeicoes_incluidas', through='core.RefeicaoDieta', to='core.dieta'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='core_usuario_set', to='auth.group', verbose_name='groups')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.perfil', verbose_name='Perfil')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='core_user_permissions_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='refeicao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='refeicoes', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietas', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='agendaalimentar',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_alimentares', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='UsuarioRestricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricao_alimentar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.restricaoalimentar')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Restrição de Usuário',
                'verbose_name_plural': 'Restrições de Usuários',
                'unique_together': {('restricao_alimentar', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='restricoes',
            field=models.ManyToManyField(related_name='usuarios', through='core.UsuarioRestricao', to='core.restricaoalimentar'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientelistacompra',
            unique_together={('ingrediente', 'lista_de_compra')},
        ),
        migrations.AlterUniqueTogether(
            name='ingredientereceita',
            unique_together={('ingrediente', 'receita')},
        ),
        migrations.AlterUniqueTogether(
            name='receitarefeicao',
            unique_together={('receita', 'refeicao')},
        ),
    ]
