# Generated by Django 5.2.8 on 2026-02-04 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_receita_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Usuário dono/autor da receita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to=settings.AUTH_USER_MODEL),
        ),
    ]
