# Generated by Django 6.0.2 on 2026-02-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_receita_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='porcao_padrao_gramas',
            field=models.IntegerField(blank=True, help_text='Porção padrão em gramas (ex: 120g de frango).', null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='porcao_padrao_ml',
            field=models.IntegerField(blank=True, help_text='Porção padrão em mililitros (ex: 200ml de leite).', null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='restricoes',
            field=models.ManyToManyField(blank=True, help_text='Restrições alimentares associadas a este ingrediente', related_name='ingredientes_restritos', to='core.restricaoalimentar'),
        ),
        migrations.AddField(
            model_name='ingredientelistacompra',
            name='quantidade_gramas',
            field=models.IntegerField(blank=True, help_text='Quantidade em gramas', null=True),
        ),
        migrations.AddField(
            model_name='ingredientelistacompra',
            name='quantidade_ml',
            field=models.IntegerField(blank=True, help_text='Quantidade em mililitros', null=True),
        ),
    ]
