# Generated by Django 6.0.2 on 2026-02-04 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ingrediente_porcao_padrao_gramas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaalimentar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendaalimentar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
