# Generated by Django 6.0.2 on 2026-02-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agendaalimentar_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='restricoes',
            field=models.ManyToManyField(blank=True, help_text='Restrições alimentares desta dieta', related_name='dietas', to='core.restricaoalimentar'),
        ),
    ]
