# Generated by Django 6.0.2 on 2026-02-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dieta_restricoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='restricaoalimentar',
            name='categorias_restritas',
            field=models.ManyToManyField(blank=True, help_text='Categorias de ingredientes que esta restrição proíbe', related_name='restricoes_alimentares', to='core.categoria'),
        ),
    ]
